# Generated by Django 3.1.2 on 2020-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_img',
            field=models.ImageField(default='', upload_to='prof/images'),
        ),
    ]
